# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  image-check:  # id of input
    description: 'tools/permission'
    required: true
    default: 'tools'
  image:
    description: 'image need check'
    required: true
outputs:
  result: # image matched of output
    description: 'The image matched'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.image-check }}
    - ${{ inputs.image }}